# Generated by Django 3.2.6 on 2021-08-29 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 29, 18, 17, 58, 790997, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 8, 29, 18, 17, 58, 789963, tzinfo=utc)),
        ),
    ]
